spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=G7k#3xV@d9!NmLqz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=e287a3a2abbdf80357147ea1b7e767e55e207c1727fcd0c73cf615e00b8e58f0
oracle.bucketName=bucket-20240817-ujy4z7-xkq9-lt6p-4r2v8-sf9y3k-adi
oracle.namespaceName=axaqwplngpdg

